[tool.flet.build.android]
project_name = "Ghost PRO Matrix"
package_name = "com.ghost.matrix.pro"
build_number = 7
permissions = [
    "INTERNET",
    "RECORD_AUDIO",
    "CAMERA",
    "WRITE_EXTERNAL_STORAGE",
    "READ_EXTERNAL_STORAGE",
    "MODIFY_AUDIO_SETTINGS"
]
