[tool.briefcase.app.ghostpro]
formal_name = "Ghost PRO"
description = "Secure Encrypted Network"
sources = ["app.py"]
# Вот эта строка говорит, где искать иконку:
icon = "resources/ghostpro" 
requires = [
    "toga-android",
]
