[tool.briefcase]
project_name = "Ghost PRO"
bundle = "com.ghost"
version = "0.0.7"

[tool.briefcase.app.ghostpro]
formal_name = "Ghost PRO"
description = "Secure Encrypted Network"
bundle = "com.ghost"
icon = "resources/ghostpro"
# Указываем, что код лежит прямо в файле ghostpro.py
sources = ["ghostpro.py"]
license = "MIT"
author = "GhostDev"
author_email = "admin@ghost.pro"

requires = [
    "toga-android",
]

[tool.briefcase.app.ghostpro.android]
build_grade_dependencies = []
