name: GHOST_V13_BUILD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install Dependencies
        run: |
          pip install flet firebase-admin
          # МЫ НЕ СТАВИМ RICH, ОН УБИВАЕТ БИЛД

      - name: Build Android APK
        # Флаг --accept-licenses автоматически принимает все соглашения
        run: flet build apk --project "GhostV13" --accept-licenses
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO_V13_Final
          path: build/apk/*.apk
