name: Build Ghost PRO
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - name: Install
        run: pip install flet firebase-admin
      - name: Build Android APK
        run: |
          # Используем только название проекта
          flet build apk --project "Ghost PRO"
      - uses: actions/upload-artifact@v4
        with:
          name: GhostPRO-APK
          path: build/apk/*.apk

        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO-Final
          path: build/apk/*.apk
