name: Build Ghost PRO
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: 4. Install Requirements
        run: |
          pip install flet firebase-admin

      - name: 5. Build Final APK
        run: |
          flet build apk --project "Ghost PRO"

      - name: 6. Save APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GhostPRO-Final
          path: build/apk/*.apk
