name: Build Ghost PRO
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - name: Install
        run: pip install flet firebase-admin cryptography
      - name: Build
        run: |
          # Убираем --package и --icon, чтобы не было ошибки unrecognized arguments
          # Используем yes для фикса EOFError
          yes | flet build apk
      - uses: actions/upload-artifact@v4
        with:
          name: GhostPRO-Final
          path: build/apk/*.apk
